# regex followed by target model name
# Use this file to override the built-in path heuristics for Unikraft trees.
.*/arch/x86/x86_64/.* x86_64
.*/arch/arm/arm64/.* arm64
.*/plat/kvm/.* platform_kvm
.*/plat/xen/.* platform_xen
